sudo: false
language: node_js
node_js:
  - '0.12'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_success:
    "curl --ftp-create-dirs -T dist/index.html -u $FTP_USER:$FTP_PASS ftp://ftp.gabrielfeitosa.com/public_html/app"
