sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_success:
    "curl --ftp-create-dirs -T dist -u $FTP_USER:$FTP_PASS ftp://ftp.gabrielfeitosa.com/app/teste"
